FROM python:3.11-slim

WORKDIR /app

# Copiar requirements
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar script del cliente simulador
COPY ./client/mqtt_client_simulator.py .

CMD ["python", "mqtt_client_simulator.py"]