services:
  # Mosquitto MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_broker
    ports:
      - "1884:1883"  # Puerto externo cambiado
      - "9002:9001"  # Puerto WebSocket cambiado
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt_network

  # FastAPI Application
  fastapi_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_mqtt_app
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    networks:
      - mqtt_network
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # MQTT Client Simulator (opcional para pruebas)
  mqtt_client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: mqtt_client_simulator
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    depends_on:
      - mosquitto
    networks:
      - mqtt_network

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_DB=mqtt_data
      - POSTGRES_USER=mqtt_user
      - POSTGRES_PASSWORD=mqtt_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - mqtt_network

  # PgAdmin (Web UI para PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_web
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mqtt.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    networks:
      - mqtt_network
    depends_on:
      - postgres

networks:
  mqtt_network:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
  postgres_data: